<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net40</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net40" Version="1.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\Dependencies\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Lidgren.Network">
      <HintPath>..\Dependencies\Lidgren.Network.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Xna.Framework">
      <HintPath>..\Dependencies\Microsoft.Xna.Framework.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Xna.Framework.Game">
      <HintPath>..\Dependencies\Microsoft.Xna.Framework.Game.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Xna.Framework.Graphics">
      <HintPath>..\Dependencies\Microsoft.Xna.Framework.Graphics.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Xna.Framework.Xact">
      <HintPath>..\Dependencies\Microsoft.Xna.Framework.Xact.dll</HintPath>
    </Reference>
    <Reference Include="Secrets Of Grindea">
      <HintPath>..\Dependencies\Secrets Of Grindea.exe</HintPath>
    </Reference>
    <Reference Include="Steamworks.NET">
      <HintPath>..\Dependencies\Steamworks.NET.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
